# Generated by Django 5.0.4 on 2024-04-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.option'),
        ),
    ]
